/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'sf': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'SF Pro Text', 'Helvetica Neue', 'Segoe UI', 'Roboto', 'sans-serif'],
        'system': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'SF Pro Text', 'Helvetica Neue', 'sans-serif'],
      },
      colors: {
        'macos-blue': '#007AFF',
        'macos-red': '#FF3B30',
        'macos-yellow': '#FFCC00',
        'macos-green': '#34C759',
        'macos-gray': '#8E8E93',
        'macos-bg': '#F2F2F7',
        'macos-sidebar': '#E5E5EA',
      },
      backdropBlur: {
        'xs': '2px',
      },
      animation: {
        'dock-bounce': 'dock-bounce 0.6s ease-in-out',
        'window-open': 'window-open 0.3s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
      },
      keyframes: {
        'dock-bounce': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'window-open': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      cursor: {
        auto: "url('/cursors/default.svg'), auto",
        default: "url('/cursors/default.svg'), default",
        pointer: "url('/cursors/handpointing.svg'), pointer",
        wait: "url('/cursors/beachball.svg'), wait",
        text: "url('/cursors/textcursor.svg'), text",
        move: "url('/cursors/move.svg'), move",
        help: "url('/cursors/help.svg'), help",
        'not-allowed': "url('/cursors/notallowed.svg'), not-allowed",
        'context-menu': "url('/cursors/contextualmenu.svg'), context-menu",
        progress: "url('/cursors/busy.svg'), progress",
        cell: "url('/cursors/cell.svg'), cell",
        crosshair: "url('/cursors/cross.svg'), crosshair",
        'vertical-text': "url('/cursors/textcursorvertical.svg'), vertical-text",
        alias: "url('/cursors/makealias.svg'), alias",
        copy: "url('/cursors/copy.svg'), copy",
        'no-drop': "url('/cursors/notallowed.svg'), no-drop",
        grab: "url('/cursors/handopen.svg'), grab",
        grabbing: "url('/cursors/handgrabbing.svg'), grabbing",
        'all-scroll': "url('/cursors/move.svg'), all-scroll",
        'col-resize': "url('/cursors/resizeleftright.svg'), col-resize",
        'row-resize': "url('/cursors/resizeupdown.svg'), row-resize",
        'n-resize': "url('/cursors/resizenorth.svg'), n-resize",
        'e-resize': "url('/cursors/resizeeast.svg'), e-resize",
        's-resize': "url('/cursors/resizesouth.svg'), s-resize",
        'w-resize': "url('/cursors/resizewest.svg'), w-resize",
        'ne-resize': "url('/cursors/resizenortheast.svg'), ne-resize",
        'nw-resize': "url('/cursors/resizenorthwest.svg'), nw-resize",
        'se-resize': "url('/cursors/resizesoutheast.svg'), se-resize",
        'sw-resize': "url('/cursors/resizesouthwest.svg'), sw-resize",
        'ew-resize': "url('/cursors/resizewesteast.svg'), ew-resize",
        'ns-resize': "url('/cursors/resizenorthsouth.svg'), ns-resize",
        'nesw-resize': "url('/cursors/resizenortheastsouthwest.svg'), nesw-resize",
        'nwse-resize': "url('/cursors/resizenorthwestsoutheast.svg'), nwse-resize",
        'zoom-in': "url('/cursors/zoomin.svg'), zoom-in",
        'zoom-out': "url('/cursors/zoomout.svg'), zoom-out",
      },
    },
  },
  plugins: [],
}